### PR TITLE
feat(deis-cli,helm-cli): add GC Shell install scripts

### PR DESCRIPTION
**Pull request by rimusz**
adds extra two deis and helm cli install scripts to be used on Google Cloud Shell VM

### CODE REVIEW

**Comment by slack** [comment]
We should throw a comment at the top of each of these files as to why we needed 'em for Google Cloud Shell. Otherwise LGTM

**Comment by rimusz** [comment]
ok, will update

**Comment by sgoings** [comment]
Might make more sense to just improve the install scripts to use an environment variable like DEIS_DOWNLOAD_ARGS and adjust curl args respectively. Then we get 0 code duplication. These two files could just be wrappers of the other install script, but set DEIS_DOWNLOAD_ARGS for the user. Even better would be modifying the install script to identify when it's being run in a GCE vm... but that's getting fancy.

**Comment by rimusz** [comment]
@sgoings I have trainings starting soon, there is no more time to mess with the current install scripts
I need those scripts to be available to download easily.
When we are near v2 GA and new helm, then we can modify the install scripts :)

**Comment by sgoings** [comment]
Could you file an issue to address this tech debt after your trainings? I understand you're crunched for time, but where there's code there will be problems, and I'd like to make sure we create a tight codebase with little duplication.

**Comment by rimusz** [comment]
here we go:
https://github.com/deis/deis.io/issues/155
https://github.com/helm/helm/issues/425

**Pull request closed without merging**
