### PR TITLE
add logo Talka

### PR DESCRIPTION
**Pull request by vtomasv**
Hi, Deis team! 
We add our logo to proyect

### CODE REVIEW

**Comment by mboersma** [comment]
@vtomasv this looks good but I can't reach the target URL https://www.kvz.cl/
I get a 522 error from CloudFlare. Is this just a temporary error or does the URL need to be updated?
screen shot 2016-10-11 at 10 54 40 am

**Comment by bacongobbler** [comment]
LGTM as well, just holding off on merging until @mboersma's comment is responded to. :)

**Comment by vtomasv** [comment]
Sorry!!! is my error the URL is http://www.kvz.cl/ :(

**Comment by bacongobbler** [comment]
Is Talka a product of Kuvasz Solutions? I can't seem to find any information or logos from the landing page. Is there a main website for Talka specifically? :)

**Comment by vtomasv** [comment]
yes! talka is a product of Kuvasz Solutions

**Comment by vtomasv** [comment]
we don't have until now a particular site web for Talka :(

**Comment by bacongobbler** [comment]
Sounds good enough for me. Thanks!

**Pull request merged**
