### PR TITLE
Release 1.5

### PR DESCRIPTION
**Pull request by mboersma**
TODO:
- [x] Catchier title and intro paragraph
- [x] Flesh out v1.5.0 summary sections
- [x] Update "What's Next" section
- [x] Generate and proofread "Community shout-outs"

### CODE REVIEW

**Comment by bacongobbler** [comment]
Some thoughts on the summary section:

## New Features

 - You can now [attach SSL certificates](http://docs.deis.io/en/latest/reference/domain-ssl/) to your applications!
 - The deis client now utilizes a [plugin architecture](https://github.com/deis/deis/pull/3177)
 - `deis config:push` has been added
 - `deis git:remote` has been added
 - the `--username`, `--password` and `--yes` flags have been added to `deis auth:cancel`
 - [private repository support](http://docs.deis.io/en/latest/using_deis/using-buildpacks/#using-private-repositories) has been added to the builder
 - A [platform-wide log drain](http://docs.deis.io/en/latest/managing_deis/platform_logging/#application-log-drain) has been added
 - [multiple profile support](https://github.com/deis/deis/pull/3367) has been added to the client
 - LDAP support has been added to the controller
 - `xip.io` domains are now allowed with `deis domains:add`
 - Our test infrastructure now deploys on EC2, providing test functionality to EC2 changes
 - integration tests can now run in parallel on https://ci.deis.io

## Improvements

 - database now commences a recovery if it is started with stale data
 - cleaned up some errors in the builder
 - the client now properly reads the response from `deis auth:cancel`
 - The EC2 contrib scripts now loop until all instances have passed their health checks
 - CORS whitelisted headers have been updated
 - `btrfs` has been replaced with `overlayfs` in the latest version of CoreOS
 - The controller now ignores etcd "key missing" errors when deleting resources

## Under the Hood

 - Bumped CoreOS to 607.0.0
 - Bumped `confd` to v0.8.0 in components to use the new `--watch` flag
 - Bumped heroku-buildpack-ruby to v134
 - Bumped fleet to v0.9.2
 - Bumped python requests lib to 2.6.0
 - Bumped gunicorn to 19.3.0
 - Bumped python-dateutil to 2.4.1
 - Bumped Sphinx to 1.3.0
 - Bumped Django to 1.6.11 security release

**Comment by bacongobbler** [comment]
hmm, what's next seems relevant to me. What needs updating on that point? :)

**Comment by bacongobbler** [comment]
Title ideas:

 - Another Month, Another Release
 - Application SSL Support
 - April 2015

I'm really bad at making titles :sheep:

**Comment by mboersma** [comment]
We need a better title and intro paragraph. Also we may want to change the scheduler section of "What's Next" according to @gabrtv, and add anything else that might go there.

Also instead of "The Deis Project is proud" maybe we should go with "stoked" to pay respect to the Great State of California? :smiling_imp:

**Comment by bacongobbler** [comment]
> Also instead of "The Deis Project is proud" maybe we should go with "stoked" to pay respect to the Great State of California?

I'm okay with this

**Comment by bacongobbler** [comment]
Manually built from this PR. LGTM!

**Comment by carmstrong** [comment]
LGTM. Nice work, boys.

**Pull request merged**
