### PR TITLE
feat(post): improving Deis provisioning through rigger

### PR DESCRIPTION
**Pull request by sgoings**
and a call for community discussion

### CODE REVIEW

**Comment by mboersma** [comment]
:+1: `rigger` looks very promising. The blog post verbiage is great, I rendered it with Jekyll to preview.

The embedded video I watched is real-time, which means .5 of it is waiting for AWS to spin up instances and pass health checks. Would it be possible to link to a sped-up ASCII-cast of this...or is that still a decompile-and-hack-the-bytecode thing as our BDFL once did? :hamster:

LGTM except maybe the video length.

**Comment by carmstrong** [comment]
We could also just remove the ASCIIcast since it's linked to from the GitHub issue. If users are interested, they can click through and watch?

**Comment by sgoings** [comment]
I'm currently recreating the Asciicasts (because I agree they're a bit too lengthy to watch).

**Comment by mboersma** [comment]
LGTM++.

**Comment by bacongobbler** [comment]
lgtm

**Pull request merged**
