### PR TITLE
Add hotelquickly logo

### PR DESCRIPTION
**Pull request by philippwiendl**
We are running Deis for a few month and would like to submit our logo for your 'Trusted by' section

### CODE REVIEW

**Comment by carmstrong** [comment]
Thanks @philippwiendl! Do you happen to have a logo with a transparent or white background? That'd better fit in with the rest of the logos.

**Comment by philippwiendl** [comment]
@carmstrong just got a new logo which should fit better

**Comment by mboersma** [comment]
Here's a preview (ignore the green semicircle, that's my pointer):
screen shot 2015-07-15 at 8 56 56 am

LGTM. http://www.hotelquickly.com/ !

**Comment by carmstrong** [comment]
Thanks @philippwiendl! I squashed your commits and merged into aaca8c73f993a92af77d4fd6c2bab66bd5703922.

**Pull request closed without merging**
