### PR TITLE
Add DemocracyOS logo

### PR DESCRIPTION
**Pull request by gvilarino**
After much back and forth we're running our Deis happily and as @gabrtv suggested, I'm submitting our logo for the 'Trusted by' section.

### CODE REVIEW

**Comment by bacongobbler** [comment]
LGTM

**Comment by gvilarino** [comment]
for the record, I tried it locally and it totally fits the size limits

**Comment by carmstrong** [comment]
> for the record, I tried it locally and it totally fits the size limits

Yep, just tried it locally. Thanks @gvilarino!

**Comment by gvilarino** [comment]
thank you all for the awesome support. Go Deis!

**Pull request merged**
