### PR TITLE
Add Botlink logo

### PR DESCRIPTION
**Pull request by msull92**
We are using Deis on AWS for our applications different services.

If you like Drones, checkout http://botlink.io

### CODE REVIEW

**Comment by mboersma** [comment]
Here's a preview from Jekyll:
screen shot 2015-07-14 at 10 04 32 am

**Comment by bacongobbler** [comment]
LGTM

**Comment by mboersma** [comment]
LGTM, but deferring to Logo Master&trade; @carmstrong.

**Comment by carmstrong** [comment]
Thanks for the screenshot so I don't have to check this out locally, @mboersma. 

Thanks for sharing, @msull92!

**Pull request merged**
