### PR TITLE
fix(install-v2.sh): update install script to download from GCS

### PR DESCRIPTION
**Pull request by arschles**
Fixes https://github.com/deis/deis.io/issues/165
Ref https://github.com/deis/workflow-cli/pull/78
Ref https://github.com/deis/workflow-cli/issues/79

### CODE REVIEW

**Comment by arschles** [comment]
Verified working on `ubuntu:14.04` Docker image:

```console
root@a7ed722ad3ea:/pwd# ./install-v2.sh 
Downloading deis-v2.0.0-linux-amd64 From Google Cloud Storage...

deis is now available in your current directory.

To learn more about deis, execute:

    $ ./deis --help

root@a7ed722ad3ea:/pwd# ./deis --version
2.0.0
```

**Comment by arschles** [comment]
Verified working on Mac OS X:

```console
ENG000656:deis.io aaronschlesinger$ deis-cli/install-v2.sh 
Downloading deis-v2.0.0-darwin-amd64 From Google Cloud Storage...

deis is now available in your current directory.

To learn more about deis, execute:

    $ ./deis --help

ENG000656:deis.io aaronschlesinger$ ./deis --version
2.0.0
```

**Comment by arschles** [comment]
Since the current `install-v2.sh` script downloads from our (deprecated) bintray URL, and that's working now, I'm opting to hold off on merging this patch in favor of further manual testing (especially since I've submitted this so soon after our [major release](https://deis.com/blog/2016/workflow-stable/))

**Comment by jackfrancis** [comment]
Manually tested new install script, looks good:

```
Francismac:tmp jackfrancis$ ls -la
total 0
drwxr-xr-x  2 jackfrancis  staff   68 Jun 13 14:50 .
drwx------+ 9 jackfrancis  staff  306 Jun 13 14:50 ..
Francismac:tmp jackfrancis$ curl https://raw.githubusercontent.com/arschles/deis-deis.io/d8cfe84f856218761e14ecd5de4a02cc00ad3f55/deis-cli/install-v2.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1590  100  1590    0     0   2055      0 --:--:-- --:--:-- --:--:--  2054
Downloading deis-v2.0.0-darwin-amd64 From Google Cloud Storage...

deis is now available in your current directory.

To learn more about deis, execute:

    $ ./deis --help

Francismac:tmp jackfrancis$ ls -la
total 20784
drwxr-xr-x  3 jackfrancis  staff       102 Jun 13 14:50 .
drwx------+ 9 jackfrancis  staff       306 Jun 13 14:50 ..
-rwxr-xr-x  1 jackfrancis  staff  10639872 Jun 13 14:50 deis
```

**Comment by arschles** [comment]
thanks @jackfrancis !

**Pull request merged**
